name: Deploy to Render

on:
  push:
    branches:
      - deployment  # Specify the branch you want to monitor for changes (deployment)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker registry
    - name: Log in to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push Docker image
    - name: Build and Push Docker Image
      run: |
        docker build --platform=linux/amd64 -t docker.io/jason202/songs4geeks:latest .
        docker push docker.io/jason202/songs4geeks:latest

    - name: Deploy to production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
